/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.pages.change-password": [],
    "filament.admin.resources.categories.index": [],
    "filament.admin.resources.categories.create": [],
    "filament.admin.resources.categories.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.option-attributes.index": [],
    "filament.admin.resources.option-attributes.create": [],
    "filament.admin.resources.option-attributes.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.options.index": [],
    "filament.admin.resources.options.create": [],
    "filament.admin.resources.options.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.products.index": [],
    "filament.admin.resources.products.create": [],
    "filament.admin.resources.products.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.super-categories.index": [],
    "filament.admin.resources.super-categories.create": [],
    "filament.admin.resources.super-categories.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.tags.index": [],
    "filament.admin.resources.tags.create": [],
    "filament.admin.resources.tags.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "locale.switch": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "home.index": [],
    "products.index": [],
    "products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "super-categories.show": [
        {
            "name": "super_category",
            "required": true
        }
    ],
    "categories.show": [
        {
            "name": "category",
            "required": true
        }
    ],
    "custom_order.index": [],
    "admin.form-builder": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
